repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: ["--config", ".ruff.toml"]
      - id: ruff-format
        args: ["--config", ".ruff.toml"]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 5.0.0
    hooks:
      - id: shellcheck
        files: "scripts/.*\.sh"
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.0
    hooks:
      - id: mypy
        additional_dependencies: ["sqlmodel"]
        args: ["--python-version", "3.12"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: ["--fix", "--config", ".ruff.toml"]
        stages: [pre-commit]
